"""users junction_environment column

Revision ID: 29842303d8f5
Revises: 57535acfa22d
Create Date: 2026-06-10 12:46:29.796668
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '29842303d8f5'
down_revision: str | None = '57535acfa22d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('junction_environment', sa.String(length=16), server_default='sandbox', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'junction_environment')
    # ### end Alembic commands ###
