"""users guest_token_hash

Revision ID: da0e1838c3e0
Revises: e3f27e56e96b
Create Date: 2026-06-10 19:42:28.425576
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'da0e1838c3e0'
down_revision: str | None = 'e3f27e56e96b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guest_token_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_guest_token_hash'), 'users', ['guest_token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guest_token_hash'), table_name='users')
    op.drop_column('users', 'guest_token_hash')
    # ### end Alembic commands ###
